export const LOAD_TARGET = 'owtf/Report/LOAD_TARGET',
  LOAD_TARGET_SUCCESS = 'owtf/Report/LOAD_TARGET_SUCCESS',
  LOAD_TARGET_ERROR = 'owtf/Report/LOAD_TARGET_ERROR';

export const LOAD_PLUGIN_OUTPUT = 'owtf/Report/LOAD_PLUGIN_OUTPUT',
  LOAD_PLUGIN_OUTPUT_SUCCESS = 'owtf/Report/LOAD_PLUGIN_OUTPUT_SUCCESS',
  LOAD_PLUGIN_OUTPUT_ERROR = 'owtf/Report/LOAD_PLUGIN_OUTPUT_ERROR';

export const CHANGE_USER_RANK = 'owtf/Report/CHANGE_USER_RANK',
  CHANGE_USER_RANK_SUCCESS = 'owtf/Report/CHANGE_USER_RANK_SUCCESS',
  CHANGE_USER_RANK_ERROR = 'owtf/Report/CHANGE_USER_RANK_ERROR';