export const LOAD_TARGET = "owtf/Report/LOAD_TARGET",
  LOAD_TARGET_SUCCESS = "owtf/Report/LOAD_TARGET_SUCCESS",
  LOAD_TARGET_ERROR = "owtf/Report/LOAD_TARGET_ERROR";

export const LOAD_PLUGIN_OUTPUT_NAMES = "owtf/Report/LOAD_PLUGIN_OUTPUT_NAMES",
  LOAD_PLUGIN_OUTPUT_NAMES_SUCCESS =
    "owtf/Report/LOAD_PLUGIN_OUTPUT_NAMES_SUCCESS",
  LOAD_PLUGIN_OUTPUT_NAMES_ERROR = "owtf/Report/LOAD_PLUGIN_OUTPUT_NAMES_ERROR";

export const LOAD_PLUGIN_OUTPUT = "owtf/Report/LOAD_PLUGIN_OUTPUT",
  LOAD_PLUGIN_OUTPUT_SUCCESS = "owtf/Report/LOAD_PLUGIN_OUTPUT_SUCCESS",
  LOAD_PLUGIN_OUTPUT_ERROR = "owtf/Report/LOAD_PLUGIN_OUTPUT_ERROR";

export const CHANGE_USER_RANK = "owtf/Report/CHANGE_USER_RANK",
  CHANGE_USER_RANK_SUCCESS = "owtf/Report/CHANGE_USER_RANK_SUCCESS",
  CHANGE_USER_RANK_ERROR = "owtf/Report/CHANGE_USER_RANK_ERROR";

export const DELETE_PLUGIN_OUTPUT = "owtf/Report/DELETE_PLUGIN_OUTPUT",
  DELETE_PLUGIN_OUTPUT_SUCCESS = "owtf/Report/DELETE_PLUGIN_OUTPUT_SUCCESS",
  DELETE_PLUGIN_OUTPUT_ERROR = "owtf/Report/DELETE_PLUGIN_OUTPUT_ERROR";

export const CHANGE_USER_NOTES = "owtf/Report/CHANGE_USER_NOTES",
  CHANGE_USER_NOTES_SUCCESS = "owtf/Report/CHANGE_USER_NOTES_SUCCESS",
  CHANGE_USER_NOTES_ERROR = "owtf/Report/CHANGE_USER_NOTES_ERROR";

export const LOAD_TARGET_EXPORT = "owtf/Report/LOAD_TARGET_EXPORT",
  LOAD_TARGET_EXPORT_SUCCESS = "owtf/Report/LOAD_TARGET_EXPORT_SUCCESS",
  LOAD_TARGET_EXPORT_ERROR = "owtf/Report/LOAD_TARGET_EXPORT_ERROR";
