export const LOAD_TARGET :string= "owtf/Report/LOAD_TARGET",
  LOAD_TARGET_SUCCESS :string= "owtf/Report/LOAD_TARGET_SUCCESS",
  LOAD_TARGET_ERROR :string= "owtf/Report/LOAD_TARGET_ERROR";

export const LOAD_PLUGIN_OUTPUT_NAMES :string= "owtf/Report/LOAD_PLUGIN_OUTPUT_NAMES",
  LOAD_PLUGIN_OUTPUT_NAMES_SUCCESS :string=
    "owtf/Report/LOAD_PLUGIN_OUTPUT_NAMES_SUCCESS",
  LOAD_PLUGIN_OUTPUT_NAMES_ERROR :string= "owtf/Report/LOAD_PLUGIN_OUTPUT_NAMES_ERROR";

export const LOAD_PLUGIN_OUTPUT :string= "owtf/Report/LOAD_PLUGIN_OUTPUT",
  LOAD_PLUGIN_OUTPUT_SUCCESS :string= "owtf/Report/LOAD_PLUGIN_OUTPUT_SUCCESS",
  LOAD_PLUGIN_OUTPUT_ERROR :string= "owtf/Report/LOAD_PLUGIN_OUTPUT_ERROR";

export const CHANGE_USER_RANK :string= "owtf/Report/CHANGE_USER_RANK",
  CHANGE_USER_RANK_SUCCESS :string= "owtf/Report/CHANGE_USER_RANK_SUCCESS",
  CHANGE_USER_RANK_ERROR :string= "owtf/Report/CHANGE_USER_RANK_ERROR";

export const DELETE_PLUGIN_OUTPUT :string= "owtf/Report/DELETE_PLUGIN_OUTPUT",
  DELETE_PLUGIN_OUTPUT_SUCCESS :string= "owtf/Report/DELETE_PLUGIN_OUTPUT_SUCCESS",
  DELETE_PLUGIN_OUTPUT_ERROR :string= "owtf/Report/DELETE_PLUGIN_OUTPUT_ERROR";

export const CHANGE_USER_NOTES :string= "owtf/Report/CHANGE_USER_NOTES",
  CHANGE_USER_NOTES_SUCCESS :string= "owtf/Report/CHANGE_USER_NOTES_SUCCESS",
  CHANGE_USER_NOTES_ERROR :string= "owtf/Report/CHANGE_USER_NOTES_ERROR";

export const LOAD_TARGET_EXPORT :string= "owtf/Report/LOAD_TARGET_EXPORT",
  LOAD_TARGET_EXPORT_SUCCESS :string= "owtf/Report/LOAD_TARGET_EXPORT_SUCCESS",
  LOAD_TARGET_EXPORT_ERROR :string= "owtf/Report/LOAD_TARGET_EXPORT_ERROR";
