"""
owtf.error_handler
~~~~~~~~~~~~~~~~~~

The error handler provides a centralised control for aborting the application
and logging errors for debugging later.
"""

import sys
import logging

from owtf.lib.exceptions import FrameworkAbortException, PluginAbortException


command = None
len_padding = 100
padding = "\n%s\n\n" % ("_" * len_padding)
sub_padding = "\n%s\n" % ("*" * len_padding)


def abort_framework(message):
    """Abort the OWTF framework.

    :warning: If it happens really early and :class:`framework.core.Core`
        has note been instantiated yet, `sys.exit()` is called with error
        code -1

    :param str message: Descriptive message about the abort.

    :return: full message explaining the abort.
    :rtype: str

    """
    message = "Aborted by Framework: {0}".format(message)
    logging.error(message)
    sys.exit(message)


def get_option_from_user(options):
    """Give the user options to select

    :param options: Set of available options for the user
    :type options: `str`
    :return: The different options for the user to choose from
    :rtype: `str`
    """
    return input("Options: 'e'+Enter= Exit %s, Enter= Next test\n".format(options))


def user_abort(level, partial_output=''):
    """This function handles the next steps when a user presses Ctrl-C

    :param level: The level which was aborted
    :type level: `str`
    :param partial_output: Partial output generated by the command or plugin
    :type partial_output: `str`
    :return: Message to present to the user
    :rtype: `str`
    """
    # Levels so far can be Command or Plugin
    logging.info("\nThe %s was aborted by the user: Please check the report and plugin output files", level)
    message = ("\nThe {0} was aborted by the user: Please check the report and plugin output files".format(level))
    if level == 'Command':
        option = 'p'
        if option == 'e':
            # Try to save partial plugin results.
            raise FrameworkAbortException(partial_output)
        elif option == 'p':  # Move on to next plugin.
            # Jump to next handler and pass partial output to avoid losing results.
            raise PluginAbortException(partial_output)
    return message
