networks:
  backend: {}
volumes:
  owtf-data: {}
services:
  owtf-backend:
    container_name: owtf-backend
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    command: ["/usr/bin/wait-for-it.sh", "db:5432", "--", "owtf"]
    environment:
      - DOCKER=1
      - POSTGRES_USER=owtf_db_user
      - POSTGRES_PASSWORD=jgZKW33Q+HZk8rqylZxaPg1lbuNGHJhgzsq3gBKV32g=
      - POSTGRES_DB=owtf_db
      - OWTF_INBOUND_PROXY_BIND_IP=0.0.0.0
    ports:
      - 127.0.0.1:8008:8008
      - 127.0.0.1:8010:8010
      - 127.0.0.1:8009:8009
    depends_on:
      - owtf-frontend
      - db
    volumes:
      - ..:/home/owtf/owtf
      - owtf-data:/home/owtf/.owtf
    networks:
      - backend
  owtf-frontend:
    container_name: owtf-frontend
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - 127.0.0.1:8019:8019
    volumes:
      - ..:/home/owtf/owtf
    networks:
      - backend
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=owtf_db_user
      - POSTGRES_PASSWORD=jgZKW33Q+HZk8rqylZxaPg1lbuNGHJhgzsq3gBKV32g=
      - POSTGRES_DB=owtf_db
    networks: 
      - backend
