export const LOAD_ERRORS = "owtf/Dashboard/LOAD_ERRORS",
  LOAD_ERRORS_SUCCESS = "owtf/Dashboard/LOAD_ERRORS_SUCCESS",
  LOAD_ERRORS_ERROR = "owtf/Dashboard/LOAD_ERRORS_ERROR";

export const CREATE_ERROR = "owtf/Dashboard/CREATE_ERROR",
  CREATE_ERROR_SUCCESS = "owtf/Dashboard/CREATE_ERROR_SUCCESS",
  CREATE_ERROR_ERROR = "owtf/Dashboard/CREATE_ERROR_ERROR";

export const DELETE_ERROR = "owtf/Dashboard/DELETE_ERROR",
  DELETE_ERROR_SUCCESS = "owtf/Dashboard/DELETE_ERROR_SUCCESS",
  DELETE_ERROR_ERROR = "owtf/Dashboard/DELETE_ERROR_ERROR";

export const LOAD_SEVERITY = "owtf/Dashboard/LOAD_SEVERITY",
  LOAD_SEVERITY_SUCCESS = "owtf/Dashboard/LOAD_SEVERITY_SUCCESS",
  LOAD_SEVERITY_ERROR = "owtf/Dashboard/LOAD_SEVERITY_ERROR";

export const LOAD_TARGET_SEVERITY = "owtf/Dashboard/LOAD_TARGET_SEVERITY",
  LOAD_TARGET_SEVERITY_SUCCESS = "owtf/Dashboard/LOAD_TARGET_SEVERITY_SUCCESS",
  LOAD_TARGET_SEVERITY_ERROR = "owtf/Dashboard/LOAD_TARGET_SEVERITY_ERROR";