/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */

 const webpack = require('webpack');
 const merge = require('webpack-merge');
 const HtmlWebpackPlugin = require('html-webpack-plugin');
 const CircularDependencyPlugin = require('circular-dependency-plugin');
 const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
 
 const develop = {
   entry: [
     'eventsource-polyfill', // Necessary for hot reloading with IE
     'webpack-hot-middleware/client?reload=true',
   ],
   mode: 'development',
   // Don't use hashes in dev mode for better performance
   output: {
     filename: '[name].js',
     chunkFilename: '[name].chunk.js'
   },
   optimization: {
     minimize: true,
     namedModules: true,
     namedChunks: true,
     removeAvailableModules: true,
     flagIncludedChunks: true,
     occurrenceOrder: false,
     usedExports: true,
     concatenateModules: true,
     sideEffects: true, // <----- in prod defaults to true if left blank
 },
 
   // Add development plugins
   plugins: [

     // new BundleAnalyzerPlugin(),
     new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
     new webpack.NoEmitOnErrorsPlugin(),
     new HtmlWebpackPlugin({
       inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
       template: 'src/index.html',
     }),
     new CircularDependencyPlugin({
       exclude: /a\.js|node_modules/, // exclude node_modules
       failOnError: false, // show a warning when there is a circular dependency
     }),
   ],
 
   // Emit a source map for easier debugging
   // See https://webpack.js.org/configuration/devtool/#devtool
   devtool: 'eval-source-map',
 
 };
 
 module.exports = merge(develop, require('./common.config'));