export const EMAIL_SEND_START = "owtf/EmailVerification/EMAIL_SEND_START",
  EMAIL_SEND_SUCCESS = "owtf/EmailVerification/EMAIL_SEND_SUCCESS",
  EMAIL_SEND_FAIL = "owtf/EmailVerification/EMAIL_SEND_FAIL",
  EMAIL_VERIFICATION_START = "owtf/EmailVerification/EMAIL_VERIFICATION_START",
  EMAIL_VERIFICATION_SUCCESS =
    "owtf/EmailVerification/EMAIL_VERIFICATION_SUCCESS",
  EMAIL_VERIFICATION_FAIL = "owtf/EmailVerification/EMAIL_VERIFICATION_FAIL";
