export const LOAD_CONFIGURATIONS = 'owtf/Configurations/LOAD_CONFIGURATIONS';
export const LOAD_CONFIGURATIONS_SUCCESS = 'owtf/Configurations/LOAD_CONFIGURATIONS_SUCCESS';
export const LOAD_CONFIGURATIONS_ERROR = 'owtf/Configurations/LOAD_CONFIGURATIONS_ERROR';

export const CHANGE_CONFIGURATIONS = 'owtf/Configurations/CHANGE_CONFIGURATIONS';
export const CHANGE_CONFIGURATIONS_SUCCESS = 'owtf/Configurations/CHANGE_CONFIGURATIONS_SUCCESS';
export const CHANGE_CONFIGURATIONS_ERROR = 'owtf/Configurations/CHANGE_CONFIGURATIONS_ERROR';
