export const LOAD_CONFIGURATIONS = 'owtf/Configurations/LOAD_CONFIGURATIONS',
    LOAD_CONFIGURATIONS_SUCCESS = 'owtf/Configurations/LOAD_CONFIGURATIONS_SUCCESS',
    LOAD_CONFIGURATIONS_ERROR = 'owtf/Configurations/LOAD_CONFIGURATIONS_ERROR';

export const CHANGE_CONFIGURATIONS = 'owtf/Configurations/CHANGE_CONFIGURATIONS',
    CHANGE_CONFIGURATIONS_SUCCESS = 'owtf/Configurations/CHANGE_CONFIGURATIONS_SUCCESS',
    CHANGE_CONFIGURATIONS_ERROR = 'owtf/Configurations/CHANGE_CONFIGURATIONS_ERROR';
