export const FORGOT_PASSWORD_EMAIL_START :string=
    "owtf/ForgotPasswordPage/FORGOT_PASSWORD_EMAIL_START",
  FORGOT_PASSWORD_EMAIL_SUCCESS :string=
    "owtf/ForgotPasswordPage/FORGOT_PASSWORD_EMAIL_SUCCESS",
  FORGOT_PASSWORD_EMAIL_FAIL:string =
    "owtf/ForgotPasswordPage/FORGOT_PASSWORD_EMAIL_FAIL";
