export const FORGOT_PASSWORD_EMAIL_START =
    "owtf/ForgotPasswordPage/FORGOT_PASSWORD_EMAIL_START",
  FORGOT_PASSWORD_EMAIL_SUCCESS =
    "owtf/ForgotPasswordPage/FORGOT_PASSWORD_EMAIL_SUCCESS",
  FORGOT_PASSWORD_EMAIL_FAIL =
    "owtf/ForgotPasswordPage/FORGOT_PASSWORD_EMAIL_FAIL";
